name: show-directory

on: push
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: make setup

      - run: make test
      
      - run: make lint
---
name: cloning

on: push
jobs:
  cloning:
  runs-on: ubuntu-latest
  steps:

      - users: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          branch: 'main'
          owner: 'K'
          repository: 'hexlet-ci-app-2'

build:
runs-on: ubuntu-latest steps
steps:
    - uses: actions/checkout@va
    - uses: actions/setup-node@u6 
      with:
        node-version: 24
    - run: make setup
    - run: make install
    - run: make test

helloFromHexlet:
  runs-on: ubuntu-latest 
  steps:
      - name: Checkout 
        id: checkout 
        uses: actions/checkout@v4

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release